# Copyright (C) 2025-2026 OrangeFox Recovery Project
# Copyright (C) 2026 ironhide
# SPDX-License-Identifier: GPL-3.0-only
#

export TW_DEFAULT_LANGUAGE="en"
export LC_ALL="C"
export ALLOW_MISSING_DEPENDENCIES=true
export FOX_USE_NANO_EDITOR=1
export FOX_ENABLE_APP_MANAGER=1
export FOX_USE_BASH_SHELL=1
export FOX_ASH_IS_BASH=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_SED_BINARY=1
export FOX_USE_XZ_UTILS=1
export FOX_DELETE_AROMAFM=1

export OF_ENABLE_FRP_ADDON="1"
export FOX_MAINTAINER_PATCH_VERSION="1"
export OF_MAINTAINER="IRONHIDE"
export OF_SCREEN_H="2460"
export OF_SCREEN_W="1080"

export FOX_USE_DATA_RECOVERY_FOR_SETTINGS="1" 
export FOX_REMOVE_AAPT="1"
export OF_SCREEN_TIMEOUT="0"
export OF_NO_TREBLE_COMPATIBILITY_CHECK="1"
export ALLOW_MISSING_DEPENDENCIES=true
export OF_USE_GREEN_LED=0
export OF_ENABLE_LPTOOLS=1
export OF_UNMOUNT_SDCARDS_BEFORE_REBOOT=1
export FOX_USE_UPDATED_MAGISKBOOT=1
export FOX_VIRTUAL_AB_DEVICE=1
export OF_AB_DEVICE_WITH_RECOVERY_PARTITION=1
export OF_FL_PATH1="/tmp/flashlight"
export OF_ADVANCED_SECURITY=1